'use strict';
const { D, O, N, F, VER, INIT, FLAG, LIST, NUM, INT, STR, COORD, ANGLE, hook } = require('./_gen_helpers');

const pos = (b) => ({
  [b + '.position']: LIST('Position', 'World position [X, Y, Z] of the trader at this spot. Y is height; with exact position off the mod snaps the trader to the ground.', { level: 'advanced' }),
  [b + '.position[]']: { ...COORD },
  [b + '.orientation']: LIST('Orientation', 'Facing of the trader as three angles in degrees. To turn a machine round, change the heading angle by 180.', { level: 'advanced' }),
  [b + '.orientation[]']: { ...ANGLE },
  [b + '.useExactPosition']: FLAG('Use exact position', '0 places the trader on the ground below the position, 1 uses the coordinates exactly (for elevated or floating spots).', { level: 'advanced' }),
  [b + '.name']: STR('Spot name', 'Name of this location. Shown to players in the move notification when the trader relocates here.'),
  [b + '.enableNotification']: FLAG('Notify on move', 'When on, players get a message when the trader moves to this spot.'),
  [b + '.showNameInNotification']: FLAG('Show spot name in notification', 'When on, the move message includes the spot name.'),
  [b + '.vehicleSpawnPosition']: LIST('Vehicle spawn position', 'Where vehicles bought at this trader appear [X, Y, Z]. Only matters for traders that sell vehicles.', { level: 'advanced', confidence: O }),
  [b + '.vehicleSpawnPosition[]']: { ...COORD, confidence: O },
  [b + '.vehicleSpawnOrientation']: LIST('Vehicle spawn orientation', 'Facing of vehicles that spawn at the vehicle position, in degrees.', { level: 'advanced', confidence: O }),
  [b + '.vehicleSpawnOrientation[]']: { ...ANGLE, confidence: O },
});
const managed = (o) => ({ ...o, internal: true, level: 'danger' });

const dt = {};
dt.dealerpoints = {
  version: VER(), isInitialized: INIT,
  dealerPointsNames: LIST('Trader names', 'The traders that exist on your server. Each name must match a file in the DealerPoints folder (file name without .json). Removing a name hides that trader.'),
  'dealerPointsNames[]': STR('Trader name', 'Name of one trader; must match a file in the DealerPoints folder.'),
};
dt['dealerpoints-files'] = {
  uniqueName: STR('Trader id', 'Internal name of this trader. It must match the file name and the entry in DealerPoints.json. Used in admin menus only; players see the display name.', { level: 'advanced' }),
  version: VER(),
  displayName: STR('Display name', 'Name players see for this trader in notifications and the trading screen.'),
  sellTax: NUM('Sell tax', 'Share of the sell price the trader keeps when a player sells. 0 means no tax, 1 means 100 percent (the player gets nothing).', { min: 0, max: 1, typical: '0 to 0.3', risk: 'Values near 1 make selling worthless.' }),
  acceptOnlyCash: FLAG('Cash only', '1 means players can only pay with cash they carry; 0 also allows other payment such as bank money where available.'),
  playSound: FLAG('Trader speaks', 'When on, the trader plays random voice lines near players.'),
  gender: F('Trader voice', 'Voice set used for the trader sounds: m for male, f for female.', { type: 'enum', enum: [{ value: 'm', label: 'Male' }, { value: 'f', label: 'Female' }], confidence: D }),
  minSoundTime: INT('Shortest pause between sounds', 'Minimum time between two voice lines.', { unit: 'seconds', min: 0, typical: '15-60' }),
  maxSoundTime: INT('Longest pause between sounds', 'Maximum time between two voice lines. Keep it at or above the minimum.', { unit: 'seconds', min: 0, typical: '15-60' }),
  enabledSounds: LIST('Enabled sound lines', 'Numbers (0 to 29) of the voice lines the trader may use. Empty uses the defaults.', { level: 'advanced' }),
  ...pos('positions[]'),
  positions: LIST('Possible positions', 'Spots the trader can stand at. With more than one, the trader moves between them at random intervals (see move times). With one, it stays put.'),
  useExactPosition: FLAG('Use exact position (deprecated)', 'Old global switch that the documentation says will be removed. Each position now has its own setting; leave as is.', { level: 'advanced' }),
  useUTCTime: FLAG('Opening hours in UTC', '0 reads the opening times in server time, 1 reads them in UTC. Only matters when opening times are set.', { risk: 'A wrong value shifts opening hours by your timezone offset.' }),
  type: STR('Trader object', 'Class name of the object players use to trade, for example a trader machine. Vending machine mods can supply other classes here; the class must exist on the server.', { type: 'classname', level: 'advanced', risk: 'An unknown class means no trader appears.' }),
  minMoveTimeMinutes: INT('Shortest time at a spot', 'Minimum minutes the trader stays before moving to another possible position. Only used with more than one position.', { unit: 'minutes', min: 0 }),
  maxMoveTimeMinutes: INT('Longest time at a spot', 'Maximum minutes the trader stays before moving on. Keep it at or above the minimum.', { unit: 'minutes', min: 0 }),
  useTraderChar: FLAG('Show a trader character', '1 spawns an NPC character next to the machine; 0 uses the machine only.'),
  traderCharType: STR('Trader character class', 'Class name of the NPC model used when the character is on, for example a survivor type.', { type: 'classname' }),
  traderCharAttachments: F('Trader clothing', 'Items the trader character wears, by slot (Gloves, Feet, Shoulder, Hips, Headgear, Legs, Melee, Eyewear, Mask, Armband, Body). Not present in every file.', { type: 'object', level: 'advanced', confidence: D }),
  'traderCharAttachments.*': STR('Item in slot', 'Class name of the item worn in this slot.', { type: 'classname' }),
  openTimes: LIST('Opening times', 'Daily time windows when the trader is open. Empty means always open.'),
  'openTimes[].openHour': INT('Opens at hour', 'Hour the trader opens, 24-hour clock.', { min: 0, max: 23, unit: 'hours' }),
  'openTimes[].openMinute': INT('Opens at minute', 'Minute the trader opens.', { min: 0, max: 59, unit: 'minutes' }),
  'openTimes[].closeHour': INT('Closes at hour', 'Hour the trader closes, 24-hour clock.', { min: 0, max: 23, unit: 'hours' }),
  'openTimes[].closeMinute': INT('Closes at minute', 'Minute the trader closes.', { min: 0, max: 59, unit: 'minutes' }),
  safeZoneEnabled: FLAG('Safe zone', 'Turns on a protected area around the trader where players are safe from damage.'),
  safeZoneRadius: INT('Safe zone radius', 'Size of the protected area around the trader.', { unit: 'metres', min: 0, typical: '30-100' }),
  safeZoneTimeout: INT('Safe zone exit delay', 'Seconds a player must be outside the area before they count as having left it and lose protection.', { unit: 'seconds', min: 0 }),
  safeZoneEnableArmband: FLAG('Armband in safe zone', 'Shows an armband on players while they are inside the safe zone so others can tell they are protected.'),
  safeZoneRemoveAnimals: FLAG('Remove animals in safe zone', 'Removes wildlife that enters the area.'),
  safeZoneRemoveInfected: FLAG('Remove infected in safe zone', 'Removes zombies that enter the area.'),
  safeZoneRemoveEAI: FLAG('Remove AI in safe zone', 'Removes AI characters (from the Expansion AI mod) that enter the area.'),
  safeZoneCleanUp: FLAG('Clean up items in safe zone', 'Removes items not on the SafeZoneCleanUp whitelist from the area, to stop junk piling up at the trader.', { risk: 'Players can lose items left in the zone, including barrels and tents, unless whitelisted.', level: 'advanced' }),
  currentPosition: managed(F('Current position (managed)', 'Where the trader stands right now. Managed by the mod; do not edit by hand.', { type: 'object', confidence: D })),
  ...Object.fromEntries(Object.entries(pos('currentPosition')).map(([k, v]) => [k, managed({ ...v, help: v.help + ' Managed by the mod, do not edit.' })])),
  nextMoveTime: managed(F('Next move time (managed)', 'When the trader will next relocate. Managed by the mod; do not edit by hand.', { type: 'object', confidence: D })),
  ...Object.fromEntries(['year', 'month', 'day', 'hour', 'minute', 'second', 'inSeconds'].map((k) => ['nextMoveTime.' + k, managed(INT('Next move: ' + k, 'Part of the scheduled next relocation time. Managed by the mod; do not edit by hand.'))])),
  uniqueFileNames: LIST('Items for sale', 'Names of the item files (in TraderItemConfigs) this trader deals in. An item only shows at traders that list it here.'),
  'uniqueFileNames[]': STR('Item file name', 'Name of one item file in TraderItemConfigs (without .json).'),
};
dt.logger = {
  version: VER(),
  logBuyCSV: FLAG('Log buys to CSV', 'Writes every purchase to a CSV file on the server.'),
  logBuyDiscord: FLAG('Log buys to Discord', 'Posts every purchase to the buy webhook address.'),
  discordBuyWebhookURL: hook('purchases'),
  logSellCSV: FLAG('Log sells to CSV', 'Writes every sale to a CSV file on the server.'),
  logSellDiscord: FLAG('Log sells to Discord', 'Posts every sale to the sell webhook address.'),
  discordSellWebhookURL: hook('sales'),
};
dt.safezonecleanup = {
  version: VER(),
  safeZoneCleanUpWhitelist: LIST('Items kept in safe zones', 'Class names of items the safe zone clean-up must not remove at restart, for example barrels. Only used by traders with clean-up on.'),
};
dt.traderitemcategorieorder = {
  version: VER(),
  'categorieOrder.*': LIST('Category order of this trader', 'Order in which item categories are listed at the trader. The key is the trader name. The mod adds new categories automatically; you only reorder them.'),
  'categorieOrder.*[]': STR('Category name', 'One category name as used in item files. Move lines to reorder; do not invent names that no item uses.'),
};
dt['traderitemconfigs-files'] = {
  uniqueName: STR('Item id', 'Name of the item entry. Must match the file name and what the traders list. Players do not see it.', { level: 'advanced' }),
  type: STR('Item class', 'Class name of the DayZ item sold or bought, as in types.xml.', { type: 'classname', risk: 'A class the server does not know breaks the entry.' }),
  currency: STR('Currency', 'Which currency is used. "default" uses the main one; other names come from the shared currency config.', { typical: 'default' }),
  category: STR('Category', 'Group the item appears under at the trader (for example Food). A new name adds a new tab.'),
  quantity: NUM('Quantity per deal', 'Amount of the item in each transaction (count, rounds or liquid, depending on the item). -1 means the maximum amount, in which case the quantity the seller holds does not affect price.', { special: { '-1': 'maximum / full' }, typical: '-1 or 1', default: -1 }),
  isPremium: FLAG('Premium only', 'Only players with premium status can buy this item.'),
  isStorageItem: FLAG('Limited stock', 'Gives the item a trader stock. Prices then move between the base and the maximum price as stock changes, and stock is limited by max storage.', { confidence: O }),
  ignoreHealth: FLAG('Ignore condition when selling', 'When on, damaged items sell for the full price instead of a reduced one.'),
  buyPrice: INT('Buy price', 'Price a player pays to buy the item. With limited stock, this is the base price.', { unit: 'coins', min: 0 }),
  maxBuyPrice: INT('Highest buy price', 'Upper price used for limited-stock items when stock runs low.', { unit: 'coins', min: 0 }),
  emptyStorageOnServerRestart: FLAG('Empty stock at restart', 'Removes all stock of this item at every server restart.', { level: 'advanced' }),
  fillStorageOnServerRestart: FLAG('Fill stock at restart', 'Fills stock to the maximum at every server restart.', { level: 'advanced' }),
  ignoreBuyStorageLimit: FLAG('Ignore stock when buying', 'Players can buy even when the stock is empty.', { level: 'advanced' }),
  ignoreSellStorageLimit: FLAG('Ignore stock limit when selling', 'Players can sell even when the stock is already full.', { level: 'advanced' }),
  sellPrice: INT('Sell price', 'What the player gets for selling the item. With limited stock this is the base price.', { unit: 'coins', min: 0 }),
  maxSellPrice: INT('Highest sell price', 'Upper price used for limited-stock items when stock is low.', { unit: 'coins', min: 0 }),
  maxStorage: INT('Maximum stock', 'Most units the trader can hold of this item.', { min: 0 }),
  reducePerTick: INT('Stock change per tick', 'Stock removed every tick, so the trader stock slowly drains. Negative values add stock instead; 0 means no change over time.', { typical: '0' }),
  tickLengthInMinutes: INT('Tick length', 'Minutes between stock ticks.', { unit: 'minutes', min: 1, typical: '10', default: 10 }),
  premiumPriceReduce: NUM('Premium discount', 'Discount for premium players.', { unit: 'percent', min: 0, max: 100 }),
  maxCountThatPlayerCanBuyAsAttachment: INT('Included attachment limit', 'How many of the included attachments (not optional ones) a player can take.', { min: 0, typical: '1' }),
  maxCountThatPlayerCanBuyAsOptionalAttachment: INT('Optional attachment limit', 'How many optional attachments a player can add.', { min: 0, typical: '1' }),
  maxBuyCount: INT('Max per purchase', 'Most units a player can buy in one go.', { min: 1, typical: '20', default: 20 }),
  enablePoints: FLAG('Use reputation', 'Switches on the reputation rules (limits and rewards below) for this item.'),
  minPointsNeededForSell: INT('Minimum reputation to sell', 'Lowest reputation to sell this item. The default (about minus 2.1 billion) means no limit.', { unit: 'points', level: 'advanced' }),
  minPointsNeededForBuy: INT('Minimum reputation to buy', 'Lowest reputation to buy this item. The default means no limit.', { unit: 'points', level: 'advanced' }),
  maxPointsNeededForSell: INT('Maximum reputation to sell', 'Highest reputation allowed to sell this item. The default (about 2.1 billion) means no limit.', { unit: 'points', level: 'advanced' }),
  maxPointsNeededForBuy: INT('Maximum reputation to buy', 'Highest reputation allowed to buy this item. The default means no limit.', { unit: 'points', level: 'advanced' }),
  givePlayerPointsForSell: INT('Points for selling', 'Reputation gained when the player sells this item. Negative values remove points.', { unit: 'points', level: 'advanced' }),
  givePlayerPointsForBuy: INT('Points for buying', 'Reputation gained when the player buys this item. Negative values remove points.', { unit: 'points', level: 'advanced' }),
  storageItem: managed(F('Stock record (managed)', 'Current stock of the item, kept by the mod. Do not edit.', { type: 'object', confidence: D })),
  attachmentUniqueNames: LIST('Included attachments', 'Item ids bought together with the item at no extra cost.'),
  optionalAttachmentUniqueNames: LIST('Optional attachments', 'Item ids a player may add for extra payment.'),
  variations: LIST('Variations', 'Other class names counted as the same item, such as colour variants of clothing.'),
  version: VER(),
};
module.exports = dt;
